name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Transfer files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: test
          
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          shell: bash -l -eo pipefail {0}
          run: nvm use 18
          script: |
            cd test
            npm install
            npm run build
            sudo cp -r dist/* /usr/share/nginx/html/
            sudo systemctl stop nginx
            sudo systemctl start nginx

            
