name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
        
      - name: Install dependencies
        run: npm install

      - name: Transfer files to EC2
        uses: appleboy/scp-action@0.1.9
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: test
      - name: SSH into EC2
        uses: appleboy/ssh-action@0.1.9
        with:
          host: ${{ secrets.EC2_IP_ADDRESS }}
          username: your-ssh-username
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd test
            npm install # 애플리케이션 종속성 설치
            npm run dev # 또는 다른 서버 실행 명령
